# -*- coding: utf-8 -*-
"""V10-P7: retail underwear — cash buffer vs put insurance.

Part 18 priced the backstop's clock: leverage is booked on the promise,
protection is probabilistic from capacity. Part 19 asks the retail
question: when protection is probabilistic, what does the retail
investor's own "underwear" look like, and what does it cost?

Two garments:

  1. cash buffer b — deterministic mitigation: every path is scaled by
     (1-b).  Cost is the steady opportunity cost b*g in calm markets.
     Capacity is 1.0 by construction: the cash never fails to be there.

  2. put insurance (deductible D, premium pi) — probabilistic tail
     truncation: only paths beyond -D get paid, and the premium must be
     renewed in the options market, which prices insurance most
     expensively exactly when it is most needed (Part 18's "pushing on
     a string", retail version).

Mirror of Part 18: the cash garment has deterministic capacity; the put
garment's capacity is priced by the market and can be repriced mid-
crisis.  The numbers below are exact output, seed 20260921, 2,000
paths per level, market losses generated by the same P4/P6 machinery.

Deterministic: same seed, same shocks, same numbers every run.
"""
import argparse
import random

from policy_space import SPACE_LEVELS, _space_params
from policy_moral_hazard import (
    DEFAULT_N_PATHS,
    DEFAULT_SEED,
    _clip,
    run_policy_moral_hazard,
    sample_inputs,
)

# garments
CASH_BUFFER = 0.20        # 20% in cash
CALM_GROWTH = 0.10        # calm-year equity return (opportunity cost base)
PUT_DEDUCTIBLE = 0.20     # insurance pays only losses beyond -20%
PUT_PREMIUM = 0.02        # calm-market annual cost (survey: 1-3%)
CRISIS_PREMIUM = 0.06     # renewal after vol spike, 2-3x (survey: 2-5x)
THRESHOLD_DEFAULT = 0.30

STRATEGIES = ("bare", "cash", "put", "put_crisis")


def market_losses(capacity, n=DEFAULT_N_PATHS, seed=DEFAULT_SEED):
    """Raw market losses for one policy-space level (same machinery as
    P6's run_mc, but returns the per-path list for strategy overlay)."""
    trigger_prob, lam_mean, lam_sigma = _space_params(capacity)
    rng = random.Random(seed)
    losses = []
    for _ in range(n):
        gamma0, shock, thresh = sample_inputs(rng)
        lam = lam_mean
        if lam_sigma > 0:
            lam = _clip(rng.gauss(lam_mean, lam_sigma), 1.0, 2.5)
        trigger = rng.random() < trigger_prob
        kwargs = dict(shock=shock, gamma0=gamma0, flip_threshold=thresh,
                      leverage_multiplier=lam, rng=rng)
        if not trigger:
            kwargs["trigger_buckets"] = 99  # betrayed path
        res = run_policy_moral_hazard(**kwargs)
        losses.append(res["total_return"])
    return losses


def strategy_losses(raw, cash_buffer=CASH_BUFFER,
                    deductible=PUT_DEDUCTIBLE, premium=PUT_PREMIUM,
                    crisis_premium=CRISIS_PREMIUM):
    """Overlay the three garments on raw per-path market losses.

    bare       : no garment, loss = raw
    cash       : (1-b)*raw (cash is there, every path)
    put        : raw + premium - max(0, -raw - deductible)
    put_crisis : same, but premium repriced at crisis level (the
                 retail "pushing on a string": renewal after the
                 vol spike costs 2-3x)
    Also returns the share of paths where the put garment pays nothing
    (premium wasted): raw > -deductible.
    """
    bare = list(raw)
    cash = [(1.0 - cash_buffer) * x for x in raw]
    put = []
    put_crisis = []
    wasted = 0
    n = len(raw)
    for x in raw:
        # loss x is negative; premium deepens the loss, payout shallowens it
        payout = max(0.0, -x - deductible)
        put.append(x - premium + payout)
        put_crisis.append(x - crisis_premium + payout)
        if -x < deductible:
            wasted += 1
    return {
        "bare": bare,
        "cash": cash,
        "put": put,
        "put_crisis": put_crisis,
        "wasted_share": wasted / n,
    }


def stats(losses, n, threshold=THRESHOLD_DEFAULT):
    s = sorted(losses)
    return {
        "mean": round(sum(s) / n, 4),
        "p10": round(s[min(n - 1, int(0.10 * (n - 1)))], 4),
        "p1": round(s[min(n - 1, int(0.01 * (n - 1)))], 4),
        "worst": round(s[0], 4),
        "jump_share": round(sum(1.0 for x in s if -x >= threshold) / n, 4),
    }


def strategy_table(n=DEFAULT_N_PATHS, seed=DEFAULT_SEED):
    rows = []
    for capacity, _, _, _ in SPACE_LEVELS:
        raw = market_losses(capacity, n=n, seed=seed)
        overlay = strategy_losses(raw)
        row = {"capacity": capacity,
               "wasted_share": overlay["wasted_share"]}
        for name in STRATEGIES:
            row[name] = stats(overlay[name], n)
        rows.append(row)
    return rows


def self_test():
    print("== retail_underwear self-test ==")

    # boundary: bare at C=0 reproduces the P6 no-backstop world
    raw0 = market_losses(0.0)
    s0 = stats(raw0, len(raw0))
    assert abs(s0["mean"] + 0.3390) < 0.005, s0
    assert abs(s0["p1"] + 0.4410) < 0.005
    print("   bare at C=0 reproduces no-backstop world OK "
          "(mean=%.4f)" % s0["mean"])

    rows = strategy_table()

    # cash garment: deterministic scaling — quantiles scale exactly
    for r in rows:
        bare_p1 = r["bare"]["p1"]
        cash_p1 = r["cash"]["p1"]
        expect = (1.0 - CASH_BUFFER) * bare_p1
        assert abs(cash_p1 - expect) < 0.001, (r["capacity"], cash_p1, expect)
    print("   cash garment scales every quantile by (1-b) OK")

    # NOTE: losses are negative — a "better" p1/mean is LARGER (closer
    # to zero).  put p1 is pinned at -(D+pi), so it is always >= bare.
    for r in rows:
        assert r["put"]["p1"] >= r["bare"]["p1"] + 1e-9, (
            "put p1 must not worsen: C=%.2f" % r["capacity"])
        assert r["put"]["mean"] >= r["bare"]["mean"] + 1e-9, (
            "put mean must not worsen: C=%.2f" % r["capacity"])
    print("   put garment (locked 2%% premium) improves p1 and mean "
          "at every C OK")

    # CRISIS RENEWAL is the failure mode: repriced at 6%, the premium
    # exceeds the average payout in the calm world (mean worse than
    # bare) while the payout still dominates in the depleted world.
    full = rows[0]
    depleted = rows[-2]
    assert full["put_crisis"]["mean"] <= full["bare"]["mean"], (
        "C=1.0: 6%% renewal must drag the mean below bare")
    assert depleted["put_crisis"]["mean"] >= depleted["bare"]["mean"], (
        "C=0.25: 6%% renewal must still beat bare")
    assert full["put_crisis"]["p1"] >= full["bare"]["p1"] + 1e-9
    print("   crisis renewal: drag at full capacity "
          "(mean %.4f vs bare %.4f), rescue at depleted capacity "
          "(mean %.4f vs bare %.4f) OK"
          % (full["put_crisis"]["mean"], full["bare"]["mean"],
             depleted["put_crisis"]["mean"], depleted["bare"]["mean"]))

    # wasted-premium share falls as capacity falls (deeper tails trigger
    # the put more often)
    shares = [r["wasted_share"] for r in rows[:-1]]
    for a, b in zip(shares, shares[1:]):
        assert a >= b - 1e-9, (a, b)
    print("   wasted-premium share monotone falling in 1-C OK "
          "(%.1f%% -> %.1f%%)" % (shares[0] * 100, shares[-1] * 100))

    # crisis renewal strictly worsens the put garment (higher premium,
    # same payout)
    for r in rows:
        assert r["put_crisis"]["p1"] <= r["put"]["p1"] + 1e-9
        assert r["put_crisis"]["mean"] <= r["put"]["mean"] + 1e-9
    print("   crisis renewal strictly worsens the put garment OK")

    # determinism
    assert strategy_table() == strategy_table()
    print("   determinism OK")

    print("   all invariants OK")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--self-test", action="store_true",
                    help="run invariants only")
    args = ap.parse_args()

    if args.self_test:
        self_test()
        return

    print("== V10-P7: retail underwear (cash buffer vs put insurance) ==")
    print("garments: cash=%d%% | put: deductible=%d%%, premium=%.0f%%/yr "
          "(crisis renewal %.0f%%)"
          % (CASH_BUFFER * 100, PUT_DEDUCTIBLE * 100,
             PUT_PREMIUM * 100, CRISIS_PREMIUM * 100))
    print("market losses: same P4/P6 machinery, seed %s, 2000 paths/level"
          % DEFAULT_SEED)

    rows = strategy_table()
    print()
    hdr = "%-6s %-11s%8s%9s%9s%9s%10s"
    print(hdr % ("C", "garment", "mean", "p10", "p1", "worst", ">30%"))
    for r in rows:
        for name in STRATEGIES:
            s = r[name]
            print("%-6.2f %-11s%8.4f%9.4f%9.4f%9.4f%10.1f"
                  % (r["capacity"], name, s["mean"], s["p10"], s["p1"],
                     s["worst"], s["jump_share"] * 100))
        print("   (put premium wasted on %.1f%% of paths)"
              % (r["wasted_share"] * 100))

    print()
    print("tail protection efficiency (vs bare, per 1% of cost):")
    print("   cash cost: %.1f%%/yr (%.0f%% buffer x %.0f%% calm return)"
          % (CASH_BUFFER * CALM_GROWTH * 100, CASH_BUFFER * 100,
             CALM_GROWTH * 100))
    print("   put cost : %.1f%%/yr (crisis renewal %.1f%%)"
          % (PUT_PREMIUM * 100, CRISIS_PREMIUM * 100))
    for r in rows:
        bare = r["bare"]["p1"]
        cash_gain = (r["cash"]["p1"] - bare) * 100
        put_gain = (r["put"]["p1"] - bare) * 100
        crisis_gain = (r["put_crisis"]["p1"] - bare) * 100
        print("   C=%.2f  bare p1=%.1f%% | cash saves %.1f pts "
              "| put saves %.1f pts | crisis-put saves %.1f pts"
              % (r["capacity"], bare * 100, cash_gain, put_gain,
                 crisis_gain))

    print()
    print("reading: the cash garment is deterministic (capacity 1.0),")
    print("the put garment is priced by the market — and its renewal is")
    print("most expensive exactly when it is most needed.")


if __name__ == "__main__":
    main()
